package model;

public class User {
	
	int iduser;
	//this value will be auto generated by the database
	String username;
	String password;
	boolean isAdmin;
	public User(String username, String password) {
		super();
		this.username = username;
		this.password = password;
		this.isAdmin = false;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	
	String getUserName() {
		return this.username;
	}
	public boolean isAdmin() {
		return isAdmin;
	}
	public void setAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}
	public int getIduser() {
		return iduser;
	}
	public String getUsername() {
		return username;
	}
	public String getPassword() {
		return password;
	}
	public void setIduser(int iduser) {
		this.iduser = iduser;
	}
	
		
	
	
	

}
